import { Download, Printer, ShieldCheck } from "lucide-react";
import { QRCodeSVG } from "qrcode.react";
import { useRef } from "react";
import AppShell from "../components/AppShell";
import Card from "../components/Card";
import Button from "../components/Button";
import PageHeader from "../components/PageHeader";
import { useApp } from "../context/AppContext";

export default function EmergencyCardPage(){
 const {patient}=useApp(); const printRef=useRef();
 return <AppShell><PageHeader eyebrow="Patient Portal" title="Emergency Card" subtitle="A clean, printable wallet-sized emergency card." action={<Button onClick={()=>window.print()}><Printer size={16}/> Print Card</Button>}/><div className="grid gap-6 lg:grid-cols-[1fr_360px]"><div className="flex justify-center"><div ref={printRef} className="w-full max-w-[560px] rounded-3xl border-2 border-slate-200 bg-white p-5 shadow-sm sm:p-7 print:shadow-none"><div className="flex items-center justify-between border-b border-slate-100 pb-4"><div><p className="text-lg font-black">CODE BLUE</p><p className="text-[10px] font-bold text-slate-400">Emergency Health ID</p></div><ShieldCheck className="text-blue-600"/></div><div className="mt-5 flex items-center justify-between gap-4"><div><p className="text-2xl font-black">{patient.name}</p><p className="mt-1 text-xs text-slate-500">{patient.emergencyId}</p></div><div className="rounded-xl border p-2"><QRCodeSVG value={`https://codeblue.demo/emergency/${patient.emergencyId}`} size={92}/></div></div><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-slate-50 p-3"><p className="text-[9px] font-extrabold uppercase text-slate-400">Blood Group</p><p className="mt-1 text-xl font-black">{patient.bloodGroup}</p></div><div className="rounded-xl bg-red-50 p-3"><p className="text-[9px] font-extrabold uppercase text-red-500">Critical Allergies</p><p className="mt-1 text-sm font-black text-red-800">{patient.allergies.join(", ")}</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-[9px] font-extrabold uppercase text-slate-400">Conditions</p><p className="mt-1 text-sm font-black">{patient.conditions.join(", ")}</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-[9px] font-extrabold uppercase text-slate-400">Emergency Contact</p><p className="mt-1 text-sm font-black">{patient.contacts[0].name}</p><p className="text-[10px] text-slate-500">{patient.contacts[0].phone}</p></div></div><p className="mt-5 text-center text-[9px] text-slate-400">QR contains only a secure emergency identifier, not medical history.</p></div></div><Card className="p-5"><h2 className="font-extrabold">Card actions</h2><p className="mt-2 text-sm leading-6 text-slate-500">Print the card or use the QR tools on your dashboard. The card is intentionally limited to emergency-critical information.</p><Button className="mt-5 w-full" onClick={()=>window.print()}><Download size={16}/> Print / Save as PDF</Button></Card></div></AppShell>;
}
