import { BellRing, Check, HeartPulse, ShieldCheck, X } from "lucide-react";
import { Link } from "react-router-dom";
import AppShell from "../components/AppShell";
import Card from "../components/Card";
import Button from "../components/Button";
import PageHeader from "../components/PageHeader";
import QRCodeCard from "../components/QRCodeCard";
import { useApp } from "../context/AppContext";

export function GuardianNotification(){
 const {guardianDecision,setGuardianDecision}=useApp();
 return <div className="min-h-screen bg-slate-100 p-4 sm:p-8"><div className="mx-auto max-w-md"><div className="mb-5 flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-600 text-white"><BellRing size={19}/></span><div><p className="text-sm font-black">CODE BLUE</p><p className="text-[11px] text-slate-500">Emergency notification</p></div></div><Card className="overflow-hidden"><div className="p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-bold text-slate-400">City Hospital</p><h1 className="mt-1 text-xl font-black">Access request</h1></div><span className="rounded-full bg-red-50 px-2.5 py-1 text-[10px] font-extrabold text-red-700">Emergency</span></div><p className="mt-5 text-sm leading-6 text-slate-600">City Hospital is requesting access to <strong className="text-slate-900">Aarav Mishra's</strong> medical profile.</p><div className="mt-5 rounded-2xl bg-slate-50 p-4"><p className="text-sm font-extrabold">Approve?</p><p className="mt-1 text-xs text-slate-500">You control access to your child's detailed medical information.</p></div>{guardianDecision&&<div className={`mt-4 rounded-xl p-3 text-sm font-bold ${guardianDecision==="approved"?"bg-emerald-50 text-emerald-700":"bg-red-50 text-red-700"}`}>{guardianDecision==="approved"?"Access approved.":"Access denied."}</div>}<div className="mt-5 grid grid-cols-2 gap-3"><Button variant="secondary" onClick={()=>setGuardianDecision("denied")}><X size={17}/> NO</Button><Button variant="success" onClick={()=>setGuardianDecision("approved")}><Check size={17}/> YES</Button></div></div></Card><p className="mt-4 text-center text-xs text-slate-400">You can also reply to this SMS with YES or NO.</p><Link to="/guardian/access-request" className="mt-5 block text-center text-sm font-extrabold text-blue-600">Open full access request →</Link></div></div>;
}

export function GuardianAccessRequest(){
 const {child,guardianDecision,setGuardianDecision}=useApp();
 return <div className="min-h-screen bg-slate-50"><header className="border-b border-slate-200 bg-white"><div className="mx-auto max-w-4xl px-4 py-4"><Link to="/"><span className="text-sm font-black text-slate-950">CODE BLUE</span></Link></div></header><main className="mx-auto max-w-2xl px-4 py-8 sm:py-14"><PageHeader eyebrow="Guardian" title="Access Request" subtitle="City Hospital is requesting access to Aarav Mishra's medical profile."/><Card className="p-5 sm:p-7"><div className="flex items-center gap-4"><div className="grid h-16 w-16 place-items-center rounded-2xl bg-blue-50 text-lg font-black text-blue-700">AM</div><div><h2 className="text-xl font-black">{child.name}</h2><p className="text-sm text-slate-500">Age {child.age} • {child.emergencyId}</p></div></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-slate-50 p-4"><p className="text-[10px] font-bold text-slate-400">Blood</p><p className="mt-1 text-lg font-black">{child.bloodGroup}</p></div><div className="rounded-xl bg-red-50 p-4"><p className="text-[10px] font-bold text-red-500">Allergy</p><p className="mt-1 text-sm font-black text-red-800">{child.allergies.join(", ")}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-[10px] font-bold text-slate-400">Condition</p><p className="mt-1 text-sm font-black">{child.conditions.join(", ")}</p></div></div><div className="mt-6 flex flex-col gap-3 sm:flex-row"><Button variant="danger" className="sm:flex-1" onClick={()=>setGuardianDecision("denied")}><X size={17}/> Deny</Button><Button variant="success" className="sm:flex-1" onClick={()=>setGuardianDecision("approved")}><Check size={17}/> Approve</Button></div>{guardianDecision&&<div className={`mt-5 rounded-xl p-4 text-sm font-bold ${guardianDecision==="approved"?"bg-emerald-50 text-emerald-700":"bg-red-50 text-red-700"}`}>{guardianDecision==="approved"?"Access approved. Hospital can continue according to granted permissions.":"Access denied. No detailed profile access has been granted."}</div>}<p className="mt-5 text-center text-xs text-slate-400">You can also reply to this SMS with YES or NO.</p></Card></main></div>;
}

export function GuardianDashboard(){
 const {child}=useApp();
 return <AppShell><PageHeader eyebrow="Guardian Portal" title="My Children" subtitle="Manage emergency information and access permissions." action={<Button variant="secondary">+ Add Child</Button>}/><div className="grid gap-5 lg:grid-cols-2"><Card className="p-5 sm:p-6"><div className="flex items-center gap-4"><div className="grid h-16 w-16 place-items-center rounded-2xl bg-blue-50 text-lg font-black text-blue-700">AM</div><div><h2 className="text-xl font-black">{child.name}</h2><p className="text-sm text-slate-500">Age {child.age} • Managed by Guardian</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Mini label="Blood" value={child.bloodGroup}/><Mini label="Allergy" value={child.allergies[0]} danger/><Mini label="Condition" value={child.conditions[0]}/></div><div className="mt-5 grid gap-2 sm:grid-cols-3"><Link to="/guardian/child-profile"><Button variant="secondary" className="w-full">View Profile</Button></Link><Link to="/guardian/child-profile"><Button variant="secondary" className="w-full">Emergency QR</Button></Link><Link to="/patient/access-logs"><Button variant="secondary" className="w-full">Access History</Button></Link></div></Card></div></AppShell>;
}

export function ChildProfile(){
 const {child}=useApp();
 return <AppShell><PageHeader eyebrow="Guardian Portal" title="Child Profile" subtitle="Emergency information managed by the guardian." action={<span className="inline-flex items-center gap-2 rounded-full bg-blue-50 px-3 py-2 text-xs font-extrabold text-blue-700"><ShieldCheck size={14}/> Managed by Guardian</span>}/><div className="grid gap-5 lg:grid-cols-[1fr_360px]"><Card className="p-5 sm:p-7"><div className="flex items-center gap-4"><div className="grid h-16 w-16 place-items-center rounded-2xl bg-blue-50 text-lg font-black text-blue-700">AM</div><div><h2 className="text-xl font-black">{child.name}</h2><p className="text-sm text-slate-500">Age {child.age} • {child.emergencyId}</p></div></div><div className="mt-7 grid gap-3 sm:grid-cols-2"><Data title="Blood Group" value={child.bloodGroup}/><Data title="Allergies" value={child.allergies.join(", ")} danger/><Data title="Conditions" value={child.conditions.join(", ")}/><Data title="Medications" value={child.medications.join(", ")}/><Data title="Emergency Contacts" value={child.contacts.map(c=>`${c.name} • ${c.phone}`).join(", ")} /></div></Card><QRCodeCard emergencyId={child.emergencyId}/></div></AppShell>;
}
function Mini({label,value,danger}){return <div className={`rounded-xl p-3 ${danger?"bg-red-50":"bg-slate-50"}`}><p className="text-[10px] font-extrabold uppercase tracking-wider text-slate-400">{label}</p><p className={`mt-1 text-sm font-black ${danger?"text-red-700":""}`}>{value}</p></div>}
function Data({title,value,danger}){return <div className={`rounded-xl p-4 ${danger?"bg-red-50":"bg-slate-50"} sm:col-span-1`}><p className="text-[10px] font-extrabold uppercase tracking-wider text-slate-400">{title}</p><p className={`mt-1.5 text-sm font-black ${danger?"text-red-800":""}`}>{value}</p></div>}
