import { useState } from "react";
import { Building2, CheckCircle2, ClipboardList, QrCode, Search, ShieldCheck } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import AppShell from "../components/AppShell";
import Card from "../components/Card";
import Button from "../components/Button";
import PageHeader from "../components/PageHeader";
import EmergencyAlert from "../components/EmergencyAlert";
import VerificationBadge from "../components/VerificationBadge";
import { useApp } from "../context/AppContext";
import Logo from "../components/Logo";

export function HospitalLogin() {
  const navigate=useNavigate();
  const {setHospitalAuthed,notify}=useApp();
  function submit(e){e.preventDefault();setHospitalAuthed(true);notify("Hospital staff access verified.");navigate("/hospital/dashboard")}
  return <div className="min-h-screen bg-slate-50"><header className="border-b border-slate-200 bg-white"><div className="mx-auto max-w-6xl px-4 py-4"><Logo/></div></header><main className="mx-auto grid max-w-6xl items-center gap-10 px-4 py-10 lg:grid-cols-2 lg:py-20"><div><span className="grid h-12 w-12 place-items-center rounded-2xl bg-blue-50 text-blue-600"><Building2 size={23}/></span><h1 className="mt-5 text-4xl font-black tracking-tight">Hospital Staff Login</h1><p className="mt-3 max-w-lg text-sm leading-6 text-slate-500">Authorized access only. Use your hospital credentials to access emergency summaries.</p><div className="mt-6 inline-flex items-center gap-2 rounded-full border border-emerald-100 bg-emerald-50 px-3 py-2 text-xs font-extrabold text-emerald-700"><ShieldCheck size={14}/> Verified healthcare access</div></div><Card className="p-6 sm:p-8"><form onSubmit={submit} className="space-y-4"><Field label="Hospital ID / License Number"/><Field label="Email Address" type="email"/><Field label="Password" type="password"/><button type="button" className="text-xs font-bold text-blue-600">Forgot password?</button><Button className="w-full">Login</Button></form></Card></main></div>;
}

export function HospitalDashboard() {
  const {patient}=useApp(); const navigate=useNavigate(); const [id,setId]=useState("");
  const submit=e=>{e.preventDefault();navigate(`/hospital/emergency-summary?emergencyId=${encodeURIComponent(id||patient.emergencyId)}`)};
  const actions=[[Search,"Search Patient","Find by Emergency ID or mobile number"],[QrCode,"Scan QR","Open a patient's emergency profile"],[ClipboardList,"Recent Accessed","Review recent emergency access"]];
  return <AppShell><PageHeader eyebrow="Hospital Staff Portal" title="City Hospital" subtitle="Emergency access workspace for authorized staff."/><Card className="p-5 sm:p-7"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-xl bg-blue-50 text-blue-600"><Search size={20}/></div><div><h2 className="font-extrabold">Find an Emergency Profile</h2><p className="text-xs text-slate-500">Enter Emergency ID, mobile number or use a QR scanner.</p></div></div><form onSubmit={submit} className="mt-5 flex flex-col gap-3 sm:flex-row"><input value={id} onChange={e=>setId(e.target.value)} placeholder="EHID-20260831-0042" className="min-h-12 min-w-0 flex-1 rounded-xl border border-slate-200 px-4 text-sm font-bold outline-none focus:border-blue-400"/><Button><Search size={17}/> Search</Button></form></Card><div className="mt-5 grid gap-4 md:grid-cols-3">{actions.map(([Icon,title,desc])=><Card hover key={title} className="cursor-pointer p-5" onClick={()=>title==="Search Patient"?navigate(`/hospital/emergency-summary?emergencyId=${patient.emergencyId}`):title==="Scan QR"?navigate(`/emergency/${patient.emergencyId}`):navigate("/patient/access-logs")}><span className="grid h-10 w-10 place-items-center rounded-xl bg-slate-50"><Icon size={19}/></span><h3 className="mt-4 font-extrabold">{title}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{desc}</p></Card>)}</div><div className="mt-5 rounded-2xl border border-blue-100 bg-blue-50 p-5"><p className="text-sm font-extrabold text-blue-900">Emergency access is logged</p><p className="mt-1 text-xs leading-5 text-blue-800">Every patient profile access records the hospital, staff member, time and reason.</p></div></AppShell>;
}

export function EmergencySummary() {
  const {patient,logAccess}=useApp(); const [authorized,setAuthorized]=useState(false); const [logged,setLogged]=useState(false);
  function access(){logAccess({hospital:"City Hospital",reason:"Emergency"});setLogged(true)}
  return <AppShell><PageHeader eyebrow="Emergency Summary" title={patient.name} subtitle="Critical information for authorized hospital staff." action={<span className="rounded-full bg-emerald-50 px-3 py-2 text-xs font-extrabold text-emerald-700">Emergency access</span>}/><div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><div className="space-y-5"><Card className="p-5 sm:p-7"><div className="grid gap-4 sm:grid-cols-3"><Stat label="Age" value={patient.age}/><Stat label="Blood Group" value={patient.bloodGroup} verified/><Stat label="Patient ID" value={patient.emergencyId}/></div></Card><EmergencyAlert items={patient.allergies}/><Card className="p-5 sm:p-7"><h2 className="text-base font-extrabold">Existing Conditions</h2><div className="mt-4 grid gap-2 sm:grid-cols-2">{patient.conditions.map(x=><div key={x} className="rounded-xl bg-slate-50 p-3 text-sm font-bold">✓ {x}</div>)}</div><h2 className="mt-7 text-base font-extrabold">Current Medications</h2><div className="mt-4 space-y-2">{patient.medications.map(x=><div key={x} className="rounded-xl bg-slate-50 p-3 text-sm font-bold">✓ {x}</div>)}</div></Card></div><div className="space-y-5"><Card className="p-5 sm:p-7"><h2 className="text-base font-extrabold">Emergency Contact</h2><p className="mt-4 text-lg font-black">{patient.contacts[0].name}</p><p className="mt-1 text-sm text-slate-500">{patient.contacts[0].phone}</p><Button variant="success" className="mt-5 w-full" onClick={()=>window.location.href=`tel:${patient.contacts[0].phone}`}>Call</Button></Card><Card className="p-5 sm:p-7"><h2 className="text-base font-extrabold">Full History</h2><p className="mt-2 text-sm leading-6 text-slate-500">Detailed history requires additional patient or guardian authorization.</p><label className="mt-4 flex gap-3 rounded-xl border border-slate-200 p-3 text-sm font-bold"><input type="checkbox" checked={authorized} onChange={e=>setAuthorized(e.target.checked)} className="accent-blue-600"/> Authorization received</label><Button className="mt-3 w-full" disabled={!authorized} onClick={access}><ShieldCheck size={17}/> View Full History</Button></Card><Card className="p-5">{logged?<div className="flex items-start gap-3 text-emerald-700"><CheckCircle2 size={20}/><div><p className="text-sm font-extrabold">Access Logged ✓</p><p className="mt-1 text-xs">City Hospital • Dr. Sharma • Just now • Emergency</p></div></div>:<p className="text-xs leading-5 text-slate-500">Viewing the emergency summary is available to authorized hospital staff. Full-history access is logged.</p>}</Card></div></div></AppShell>;
}
function Field({label,type="text"}){return <label className="block"><span className="mb-1.5 block text-xs font-extrabold">{label}</span><input required type={type} className="min-h-12 w-full rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-blue-400"/></label>}
function Stat({label,value,verified}){return <div className="rounded-xl bg-slate-50 p-4"><p className="text-[10px] font-extrabold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1.5 break-all text-lg font-black">{value}</p>{verified&&<VerificationBadge status="Hospital Verified"/>}</div>}
